branches:
  only:
  - master
  - release

dist: trusty
language: python

matrix:
  include:
    ###############################################################################
    # Job #1 - SQF validation
    ###############################################################################
    - python: '3.5'
      before_script:
      - pip3 install sqflint
      script:
      - python3 tools/sqf_validator.py
      - sqflint -d serverAddons/AAW/addons
    ###############################################################################
    # Job #2 - Building Extensions Disabled because not working :(
    ###############################################################################
    #- language: csharp
    #  before_install:
    #  - cd extensions
    #  - cd CLib
    #  solution: CLib.sln
