branches:
  only:
  - master
  - release

dist: trusty
language: python

matrix:
  include:
    ###############################################################################
    # Job #1 - SQF validation
    ###############################################################################
    - python: '3.5'
      before_script:
      - cd tools
      script:
      - python3 sqf_validator.py

    ###############################################################################
    # Job #2 - Building Extensions
    ###############################################################################
    - language: csharp
      solution: ./Extensions/CLib/CLib.sln